### PR TITLE
Fix Ember-Cli-Babel Deprecation

### PR DESCRIPTION
**Pull request by flexyford**
I understand this addon is "unmaintainted", but I'm hopeful that a contributor can merge this pull request to squash a deprecation warning. 

Our team is on `ember 2.18.2` and we've been getting a deprecation warning that `ember-cli-babel 5.x has been deprecated`. 

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: fitbot-client -> ember-hold-button -> ember-cli-babel
```

I came across a fork of this addon https://github.com/topaxi/ember-hold-button which fixes these deprecation warning. I have forked that repo and am hopeful this can be merged to clean up these warnings.

### CODE REVIEW

**Comment by flexyford** [comment]
Ah good ole' failing tests. I will fix those up, but am still curious if there are any contributors who would be able to merge this when passing

**Comment by chrissloey** [comment]
@flexyford yep I'll merge it if you fix the tests 👍

**Comment by flexyford** [comment]
Tests are all fixed up. 

Had to update the ‘this.off’ methods for beta and canary builds in https://github.com/AddJam/ember-hold-button/commit/2bb34abc70a2c5366c11bbd85f09cb0ec496adb9

**Comment by chrissloey** [comment]
@flexyford Merged and released a new version, thanks for doing this 😄

**Comment by flexyford** [comment]
@chrissloey Thanks for the merge and cutting a new release

**Pull request merged**
